app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Routes File
|--------------------------------------------------------------------------
|
| Here is where you will register all of the routes in an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| This route group applies the "web" middleware group to every route
| it contains. The "web" middleware group is defined in your HTTP
| kernel and includes session state, CSRF protection, and more.
|
*/

Route::group(['middleware' => ['web']], function () {
	// Authentication Routes
	Route::get('auth/login', ['as' => 'login', 'uses' => 'Auth\AuthController@getLogin']);
	Route::post('auth/login', 'Auth\AuthController@postLogin');
	Route::get('auth/logout', ['as' => 'logout', 'uses' => 'Auth\AuthController@getLogout']);

	// Registration Routes
	Route::get('auth/register', 'Auth\AuthController@getRegister');
	Route::post('auth/register', 'Auth\AuthController@postRegister');

	// Password Reset Routes
	Route::get('password/reset/{token?}', 'Auth\PasswordController@showResetForm');
	Route::post('password/email', 'Auth\PasswordController@sendResetLinkEmail');
	Route::post('password/reset', 'Auth\PasswordController@reset');

	// Categories
	Route::resource('categories', 'CategoryController', ['except' => ['create']]);
	Route::resource('tags', 'TagController', ['except' => ['create']]);
	
	// Comments
	Route::post('comments/{post_id}', ['uses' => 'CommentsController@store', 'as' => 'comments.store']);
	Route::get('comments/{id}/edit', ['uses' => 'CommentsController@edit', 'as' => 'comments.edit']);
	Route::put('comments/{id}', ['uses' => 'CommentsController@update', 'as' => 'comments.update']);
	Route::delete('comments/{id}', ['uses' => 'CommentsController@destroy', 'as' => 'comments.destroy']);
	Route::get('comments/{id}/delete', ['uses' => 'CommentsController@delete', 'as' => 'comments.delete']);


	Route::get('job/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+');
	Route::get('jobs', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);
    Route::get('contact', 'PagesController@getContact');
    Route::post('contact', 'PagesController@postContact');
	Route::get('about', 'PagesController@getAbout');
	Route::get('/', 'PagesController@getIndex');
	Route::resource('posts', 'PostController');

	// Users
	Route::get('allUsers', ['uses' => 'UserController@getAllUsers', 'as' => 'getAllUsers' ]);


	// upload images
	Route::post('/images-save', 'PostController@uploadfiles');
	Route::post('/images-delete', 'UploadImagesController@destroy');
	Route::get('/images-show', 'UploadImagesController@index');

});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
    */
    protected $fillable = [
        'id', 'type_id', 'title' , 'q1', 'q2', 'q3' , 'q4' , 'q5'. 'q6', 'q7' , 'q8' , 'q9' , 'q10' , 'q11' , 'q12' , 'q13', 'status'
    ];

    public function category()
    {
    	return $this->belongsTo('App\Category');
    }

    public function status()
    {
        return $this->belongsTo('App\PostStatus');
    }

    public function tags()
    {
    	return $this->belongsToMany('App\Tag');
    }

    public function comments()
    {
    	return $this->hasMany('App\Comment');
    }

    public function rooms()
    {
    	return $this->hasMany('App\RoomDimensions');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Post;
use App\Tag;
use App\Category;
use App\PostMediaFiles;
use Session;
use Purifier;
use Image;
use Auth;
use App\PostStatus;
use Illuminate\Support\Facades\Response;

class PostController extends Controller
{

    private $photos_path;

    public function __construct() {
        $this->middleware('auth');
        $this->photos_path = public_path('/images');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id = null)
    {
        $role_id = Auth::user()->role_id;
        $id = Auth::user()->id;

        $postStatus = \App\PostStatus::get();
        // return $postStatus;


         if($role_id == 1) {
            $posts = Post::orderBy('id', 'desc')->paginate(10);
         }
         else {
            $posts= Post::where('user_id','=', $id)
            ->orderBy('id', 'desc')->paginate(10);
         }
        // $posts =$getAllPosts
                       
        return view('posts.index')->withPosts($posts)->with('postStatus',$postStatus);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::all();
        $tags = Tag::all();
        return view('posts.create')->withCategories($categories)->withTags($tags);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // validate the data
        $this->validate($request, array(
                'job_title'         => 'required|max:255',
                // 'slug'          => 'required|alpha_dash|min:5|max:255|unique:posts,slug',
                'category_id'   => 'required|integer',
                'job_details'          => 'required',
                'user_id' => 'required'
            ));

        // store in the database
        $post = new Post;
        $post->user_id = $request->user_id;
        $post->title = $request->job_title;
        $post->postal_code = $request->postal_code;
        $post->slug = str_random(30);
        $post->category_id = $request->category_id;
        $post->body = $request->job_details;
        $post->address = $request->job_address;
        $post->status = 1 ;
        $post->q1 = $request->q1;
        $post->q2 = $request->q2;
        $post->q3 = $request->q3;
        $post->q4 = $request->q4;
        $post->q5 = $request->q5;
        $post->q6 = $request->q6;
        $post->q7 = $request->q7;
        $post->q8 = $request->q8;
        $post->q9 = $request->q9;
        $post->q10 = $request->q10;
        $post->q11 = $request->q11;
        $post->q12 = $request->q12;
        $post->q13 = $request->q13;
        $postRoomDimensions = $request->room_dimensions;


        $post->save();

            // $product = PostMediaFiles::create($request->all());
            $files = array_filter($request->filename);
            foreach ( $files as $photo) {
                // $photo = $request->file('featured_img');

                if($photo){
                    $filename =$photo->getClientOriginalName();
                    $location = public_path('images/' . $filename);
                   Image::make($photo)->save($location);
                    $mediaFiles = new PostMediaFiles();
                    $mediaFiles->post_id = $post->id;
                    $mediaFiles->filename = $filename;
                    $mediaFiles->save();
                } 
            }   
            // return 'Upload successful!';

        //   if ($request->hasFile('featured_img')) {
        //     $image = $request->file('featured_img');
        //     $filename = time() . '.' . $image->getClientOriginalExtension();
        //     $location = public_path('images/' . $filename);
        //     Image::make($image)->resize(800, 400)->save($location);
        //     $mediaFiles->post_id = $post->id;
        //     $post->image = $filename;
        //     // $mediaFiles->save();
        //   }

        Session::flash('success', 'The blog post was successfully save!');

        //   if ($request->hasFile('featured_img3')) {
        //     $image = $request->file('featured_img3');
        //     $filename = time() . '.' . $image->getClientOriginalExtension();
        //     $location = public_path('images/' . $filename);
        //     Image::make($image)->resize(800, 400)->save($location);
        //     $mediaFiles->post_id = $post->id;
        //     $mediaFiles->filename = $filename;
        //     $mediaFiles->save();
        //   }
        //   if ($request->hasFile('featured_img4')) {
        //     $image = $request->file('featured_img4');
        //     $filename = time() . '.' . $image->getClientOriginalExtension();
        //     $location = public_path('images/' . $filename);
        //     Image::make($image)->resize(800, 400)->save($location);
        //     $mediaFiles->post_id = $post->id;
        //     $mediaFiles->filename = $filename;
        //     $mediaFiles->save();
        //   }
        //   if ($request->hasFile('featured_img5')) {
        //     $image = $request->file('featured_img5');
        //     $filename = time() . '.' . $image->getClientOriginalExtension();
        //     $location = public_path('images/' . $filename);
        //     Image::make($image)->resize(800, 400)->save($location);
        //     $mediaFiles->post_id = $post->id;
        //     $mediaFiles->filename = $filename;
        //     $mediaFiles->save();
        //   }
        //   if ($request->hasFile('featured_img6')) {
        //     $image = $request->file('featured_img6');
        //     $filename = time() . '.' . $image->getClientOriginalExtension();
        //     $location = public_path('images/' . $filename);
        //     Image::make($image)->resize(800, 400)->save($location);
        //     $mediaFiles->post_id = $post->id;
        //     $mediaFiles->filename = $filename;
        //     $mediaFiles->save();
        //   }
        //   if ($request->hasFile('featured_img7')) {
        //     $image = $request->file('featured_img7');
        //     $filename = time() . '.' . $image->getClientOriginalExtension();
        //     $location = public_path('images/' . $filename);
        //     Image::make($image)->resize(800, 400)->save($location);
        //     $mediaFiles->post_id = $post->id;
        //     $mediaFiles->filename = $filename;
        //     $mediaFiles->save();
        //   }
        //   if ($request->hasFile('featured_img8')) {
        //     $image = $request->file('featured_img8');
        //     $filename = time() . '.' . $image->getClientOriginalExtension();
        //     $location = public_path('images/' . $filename);
        //     Image::make($image)->resize(800, 400)->save($location);
        //     $mediaFiles->post_id = $post->id;
        //     $mediaFiles->filename = $filename;
        //     $mediaFiles->save();
        //   }
          
        // // save room dimensions for each post
        $temp_post_id = $post->id;
        $count_postRoomDimensions = count($postRoomDimensions['description']);
        $temp123 = \DB::transaction(function () use (&$postRoomDimensions,
                                                    &$temp_post_id,
                                                    $count_postRoomDimensions
            ){
            for($x=0; $x<$count_postRoomDimensions; $x++){
                $post_room_dimensions_temp = \App\RoomDimensions::create([
                        'post_id'=>$temp_post_id,
                        'description'=>$postRoomDimensions['description'][$x],
                        'length'=>$postRoomDimensions['length'][$x],
                        'width'=>$postRoomDimensions['width'][$x],
                        'height'=>$postRoomDimensions['height'][$x]
                    ]);
            }
        });
        // // end room dimensions save

        // // $post->tags()->sync($request->tags, false);

        Session::flash('success', 'The blog post was successfully save!');

        return redirect()->route('posts.show', $post->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $images = PostMediaFiles::where('post_id','=',$id)->get();
        // dd($images);
        $post = Post::find($id);
        $postStatus = \App\PostStatus::get();
        $rooms = \App\RoomDimensions::where('post_id','=',$id)->get();
        $postRoomsDimensions_array = [];
        if($rooms){
            foreach($rooms as $temp){
                array_push($postRoomsDimensions_array, array(
                                                        'length'=>$temp->length,
                                                        'height'=>$temp->height,
                                                        'width'=>$temp->width,
                                                        'description'=>$temp->description
                                                    ));
            }
        }
        return view('posts.show')->withPost($post)->with('postRoomsDimensions_array',$postRoomsDimensions_array)->with('images',$images)->with('postStatus', $postStatus);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $rooms = \App\RoomDimensions::where('post_id','=',$id)->get();
        // return $rooms;
        $postRoomsDimensions_array = [];
        if($rooms){
            foreach($rooms as $temp){
                array_push($postRoomsDimensions_array, array(

resources/views/posts/create.blade.php
@extends('main')

@section('title', '| Create New Post')

@section('stylesheets')
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
	{!! Html::style('css/parsley.css') !!}
	{!! Html::style('css/select2.min.css') !!}
	<link rel="stylesheet" href="{{asset('css/dropzone.css')}}">
	<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>

<script>
		tinymce.init({
			selector: 'textarea',
			plugins: 'link code',
			menubar: false
		});

$(document).ready(function() {
	var limit = 8;
	var i = 1;
	$(".btn-success").click(function(){
		if (i < limit){ 
			var html = $(".clone").html();
			$(".increment").after(html);
			i++;
		}
		else{
			alert("Limit Excced");
		}
	});

	$("body").on("click",".btn-danger",function(){ 
		$(this).parents(".control-group").remove();
		i--;
	});

});
</script>

@endsection

@section('content')

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h1>Create New Post</h1>
			<hr>
			<!-- <form id="create-post-form" class="data-parsley-validate"> -->
			{!! Form::open(array( 'id'=>'create-post-form' ,'route' => 'posts.store',  'data-parsley-validate' => '', 'files' => 'true', 'enctype' => 'multipart/form-data')) !!}
				<!-- {{ Form::label('title', 'Title:') }}
				{{ Form::text('title', null, array('class' => 'form-control', 'required' => '', 'maxlength' => '255')) }}  -->

				<!-- {{ Form::label('slug', 'Slug:') }}
				{{ Form::text('slug', null, array('class' => 'form-control', 'required' => '', 'minlength' => '5', 'maxlength' => '255') ) }} -->

				{{ Form::label('category_id', 'Category:') }}
				<select class="form-control" name="category_id">
					@foreach($categories as $category)
						<option value='{{ $category->id }}'>{{ $category->name }}</option>
					@endforeach

				</select>
				<input type="hidden" name="user_id" value="{{Auth::user()->id}}">

				<!-- {{ Form::label('tags', 'Tags:') }}
				<select class="form-control select2-multi" name="tags[]" multiple="multiple">
					@foreach($tags as $tag)
						<option value='{{ $tag->id }}'>{{ $tag->name }}</option>
					@endforeach

				</select> -->
				<div class="input-group control-group increment" >
					<input type="file" name="filename[]" class="form-control">
					<div class="input-group-btn"> 
						<button class="btn btn-success" type="button"><i class="glyphicon glyphicon-plus"></i>Add</button>
					</div>
					</div>
					<div class="clone hide">
					<div class="control-group input-group" style="margin-top:10px">
						<input type="file" name="filename[]" class="form-control">
						<div class="input-group-btn"> 
						<button class="btn btn-danger" type="button"><i class="glyphicon glyphicon-remove"></i> Remove</button>
						</div>
					</div>
				</div>
				
				<!-- <div class="col-md-12">
				{{ Form::label('featured_img', 'Upload a Featured Image') }}
				{{ Form::file('featured_img') }}
				</div> -->
				<!-- <div class="col-md-12">
				{{ Form::label('featured_img', 'Upload a Featured Image') }}
				{{ Form::file('featured_img[]') }}
				</div> -->
				<?php
				$post = null;
				?>
				@include('posts.templates.questionsTemplate');
				
				{{ Form::submit('Create Post', array('id'=>'submit-all', 'class' => 'btn btn-success btn-lg btn-block', 'style' => 'margin-top: 20px;')) }}
			{!! Form::close() !!}
		</div>
	</div>

@endsection


@section('scripts')

	{!! Html::script('js/parsley.min.js') !!}
	{!! Html::script('js/select2.min.js') !!}

	<script type="text/javascript">
		$('input').on('blur', function() {
			if ($("#create-post-form").valid()) {
				$('#submit-all').prop('disabled', false);  
			} else {
				$('#submit-all').prop('disabled', 'disabled');
			}
		});
		$('.select2-multi').select2();
	
		var total_photos_counter = 0;
		Dropzone.options.myDropzone = {
			// Prevents Dropzone from uploading dropped files immediately
  			autoProcessQueue: false,
			uploadMultiple: true,
			parallelUploads: 2,
			maxFilesize: 10,
			previewTemplate: document.querySelector('#preview').innerHTML,
			addRemoveLinks: true,
			dictRemoveFile: 'Remove file',
			dictFileTooBig: 'Image is larger than 16MB',
			timeout: 10000,

			init: function () {
				var submitButton = document.querySelector("#submit-all");
				myDropzone = this; // closure
				submitButton.addEventListener("click", function() {
				myDropzone.processQueue(); // Tell Dropzone to process all queued files.
				});
				this.on("removedfile", function (file) {
					$.post({
						url: '/images-delete',
						data: {id: file.name, _token: $('[name="_token"]').val()},
						dataType: 'json',
						success: function (data) {
							total_photos_counter--;
							$("#counter").text("# " + total_photos_counter);
						}
					});
				});
			},
			success: function (file, done) {
				total_photos_counter++;
				$("#counter").text("# " + total_photos_counter);
			}
		};
	</script>
	
@endsection

resources/views/posts/edit.blade.php
@extends('main')

@section('title', '| Edit Job Post')

@section('stylesheets')

	{!! Html::style('css/select2.min.css') !!}

<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>


	<script>
		tinymce.init({
			selector: 'textarea',
			plugins: 'link code',
			menubar: false
		});
	</script>

@endsection

@section('content')

	<div class="row">
		{!! Form::model($post, ['route' => ['posts.update', $post->id], 'method' => 'PUT']) !!}
		<div class="col-md-8">
			<!-- {{ Form::label('title', 'Title:') }}
			{{ Form::text('title', null, ["class" => 'form-control input-lg']) }} -->

			<!-- {{ Form::label('slug', 'Slug:', ['class' => 'form-spacing-top']) }}
			{{ Form::text('slug', null, ['class' => 'form-control','hidden']) }} -->

			{{ Form::label('category_id', "Category:", ['class' => 'form-spacing-top']) }}
			{{ Form::select('category_id', $categories, null, ['class' => 'form-control']) }}

			<!-- {{ Form::label('tags', 'Tags:', ['class' => 'form-spacing-top']) }}
			{{ Form::select('tags[]', $tags, null, ['class' => 'form-control select2-multi', 'multiple' => 'multiple']) }} -->
			
			<!-- {{ Form::label('body', "Body:", ['class' => 'form-spacing-top']) }}
			{{ Form::textarea('body', null, ['class' => 'form-control']) }} -->
		@include('posts.templates.questionsTemplate');

		</div>
		<div class="col-md-4">
			<div class="well">
				<dl class="dl-horizontal">
					<dt>Created At:</dt>

					<dd>{{ date('M j, Y h:ia', strtotime($post->created_at)) }}</dd>
				</dl>

				<dl class="dl-horizontal">
					<dt>Last Updated:</dt>
					<dd>{{ date('M j, Y h:ia', strtotime($post->updated_at)) }}</dd>
				</dl>
				<hr>
				<dl class="dl-horizontal">
					<dt>Status:</dt>
					<dd>
					@foreach($postStatus as $status)
					@if($status->id == $post->status)
					<input type="radio" name="status" id="status" value="{{$status->id}}" checked="checked">
					@else
					<input type="radio" name="status" id="status" value="{{$status->id}}">
					@endif
					{{$status->name}} <br>
					@endforeach
					</dd>
				</dl>
				<hr>
				<div class="row">
					<div class="col-sm-6">
						{!! Html::linkRoute('posts.show', 'Cancel', array($post->id), array('class' => 'btn btn-danger btn-block')) !!}
					</div>
					<div class="col-sm-6">
						{{ Form::submit('Save Changes', ['class' => 'btn btn-success btn-block']) }}
					</div>
				</div>

			</div>
		</div>
		{!! Form::close() !!}
	</div>	<!-- end of .row (form) -->

@stop

@section('scripts')

	{!! Html::script('js/select2.min.js') !!}

<script type="text/javascript">

	$('.select2-multi').select2();
	$('.select2-multi').select2().val({!! json_encode($post->tags()->getRelatedIds()) !!}).trigger('change');
	var postRoomsDimensions = [];
    @if($postRoomsDimensions_array)
    postRoomsDimensions = '{{json_encode($postRoomsDimensions_array)}}';
	postRoomsDimensions = JSON.parse(postRoomsDimensions.replace(/&quot;/g,'"'));
	// console.log(postRoomsDimensions);  
	@else
	// alert();
	@endif
	for(var x=0; x < postRoomsDimensions.length; x++){
        $('#room_dimentions').append(`
            <label for="validationCustom02">Room `+x+`: Details</label>
                <div class="form-row">
                    <div class="col-md-3 mb-3">
                        <label for="validationCustom02">Length</label>
                        <input type="number" min=0 class="form-control" id="length" name="room_dimensions[length][]" value=`+postRoomsDimensions[x]['length']+` placeholder="Length" required>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="validationCustom02">Height</label>
                        <input type="number" min=0 class="form-control" id="height" name="room_dimensions[height][]" value=`+postRoomsDimensions[x]['height']+` placeholder="Height" required>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="validationCustom02">Width</label>
                        <input type="number" min=0 class="form-control" id="width" name="room_dimensions[width][]" value=`+postRoomsDimensions[x]['width']+` placeholder="Width" required>
                    </div>
                    <div class="col-md-3 mb-3">
                        <label for="validationCustom02">Description</label>
                        <textarea type="text" class="form-control" rows="3" id="description" name="room_dimensions[description][]" placeholder="Description" required>`+postRoomsDimensions[x]['description']+`</textarea>
                    </div>
                </div>
            `);
    }

var title = "{{$post->title}};";
var postal_code = "{{$post->postal_code}};";
var address = "{{$post->address}};"

var q1=JSON.parse("{{ json_encode($post->q1) }}".replace(/&quot;/g,'"'));
var q2=JSON.parse("{{ json_encode($post->q2) }}".replace(/&quot;/g,'"'));
var q3=JSON.parse("{{ json_encode($post->q3) }}".replace(/&quot;/g,'"'));
var q4=JSON.parse("{{ json_encode($post->q4) }}".replace(/&quot;/g,'"'));
var q5=JSON.parse("{{ json_encode($post->q5) }}".replace(/&quot;/g,'"'));
var q6=JSON.parse("{{ json_encode($post->q6) }}".replace(/&quot;/g,'"'));
var q7=JSON.parse("{{ json_encode($post->q7) }}".replace(/&quot;/g,'"'));
var q8=JSON.parse("{{ json_encode($post->q8) }}".replace(/&quot;/g,'"'));
var q9=JSON.parse("{{ json_encode($post->q9) }}".replace(/&quot;/g,'"'));
var q10=JSON.parse("{{ json_encode($post->q10) }}".replace(/&quot;/g,'"'));
var q11=JSON.parse("{{ json_encode($post->q11) }}".replace(/&quot;/g,'"'));
var q12=JSON.parse("{{ json_encode($post->q12) }}".replace(/&quot;/g,'"'));
var q13=JSON.parse("{{ json_encode($post->q13) }}".replace(/&quot;/g,'"'));
</script>
<script src="{{asset('/js/checkbox_values.js')}}"></script>

@endsection

resources/views/posts/index.blade.php
@extends('main')

@section('title', '| All Jobs')

@section('content')

	<div class="row">
		<div class="col-md-10">
			<h1>All Jobs</h1>
		</div>
	@if(Auth::User()->role_id == 3)
		<div class="col-md-2">
			<a href="{{ route('posts.create') }}" class="btn btn-lg btn-block btn-primary btn-h1-spacing">Create New Job</a>
		</div>
	@endif
		<div class="col-md-12">
			<hr>
		</div>
	</div> <!-- end of .row -->

	<div class="row">
		<div class="col-md-12">
			<table class="table">
				<thead>
					<th>Title</th>
					<th>Body</th>
					<th>Created At</th>
					<th></th>
				</thead>

				<tbody>
					
					@foreach ($posts as $post)
						
						<tr>
							<td>{{ $post->title }}</td>
							<td>{{ substr(strip_tags($post->body), 0, 50) }}{{ strlen(strip_tags($post->body)) > 50 ? "..." : "" }}</td>
							<td>{{ date('M j, Y', strtotime($post->created_at)) }}</td>
							<td><a href="{{ route('posts.show', $post->id) }}" class="btn btn-default btn-sm">View</a> 
							@if(Auth::User()->role_id == 1)
							<a href="{{ route('posts.edit', $post->id) }}" class="btn btn-default btn-sm">Edit</a>
							<!-- <select name="status" id="status" disabled> -->
							@foreach($postStatus as $postS)
								@if($postS->id == $post->status)
								<button value="{{$postS->id}}" disabled>{{$postS->name}}</button>
								@else
								<!-- <button value="{{$postS->id}}">{{$postS->name}}</button> -->
								@endif
							@endforeach
							<!-- <option value="2"></option> -->
							<!-- <option value="3"></option> -->
							<!-- </select> -->
							@endif
							</td>
						</tr>

					@endforeach

				</tbody>
			</table>

			<div class="text-center">
				{!! $posts->links(); !!}
			</div>
		</div>
	</div>

@stop